baseURL = 'https://localhost/'
languageCode = 'en-us'
title = 'Costs of Disagreement - An Exhibition'

[params]
  exhibitionName = "Costs of Disagreement"
  exhibitionSubtitle = "A somber look on the cost of armed conflict"
  exhibitionDescription = "Description"
  exhibitionVenue = "Joey Soroka"
  exhibitionDate = "All the time"
  curatorNote = "Curated by Joey Soroka"
